const globalStyles = {
  flexCenter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  flexCenterEvenly: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  flexRowCenter: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  flexCenterBetween: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  flexRowCenterBetween: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  flexRowCenterEvenly: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  flexColumnEvenly: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-evenly",
  },
};
const colors = {
  white: "#FFFFFF",
  brown: "#3b1d1d",
  brownLight: "#484848",
  yellowLight: "#c5bd5f",
  lightWhite: "#f7f6e4",
  buttonGray: "#DDDDDD",
  lightBrown: "#313131",
  grey: "#a3a3a3",
  yellow: "#9d874a",
  primaryBrown: "#231917",
  lightRed: "#e95740",
  lightGray: "#898989",
  primaryGray: "#9e9e9e",
  black: "#565454",
  mediumGrey: "#c2c3be",
  lightestGrey: "#f8f4f4",
  normalBlack: "#373737",
  normalBrown: "#532d20",
  normalGrey: "#f4f4f4",
  whiteBrown: "#936c5b",
  green: "#d4ec64",
  trueBrown: "#391e1e",
  red: "#ff0000",
  blue: "#4d86c5",
  lightBlue: "#55aeb4",
  brownLightest: "#d4cc6c",
  transparent: "transparent",
  darkBrown: "#323333",
  yellowLightest: "#f1eed0",
  blackest: "#080404",
  lightestRed: "#f05c54",
  darkRed: "#d05c4c",
  lightBlack: "#242526",
  darkGrey: "#4c4c4c",
  blueLighter: "#2487fc",
  lightestBrown: "#c8943c",
};
const sizes = {
  base: 8,
  small: 12,
  font: 13,
  title: 14,
  medium: 16,
  large: 18,
  extraLarge: 24,
  huge: 36,
};
export { globalStyles, colors, sizes };
