export { default as Home } from "./Home/index";
export { default as Login } from "./Login/index";
export { default as Register } from "./Register/index";
export { default as Blog } from "./BlogPage/index";
export { default as TourDetail } from "./TourDetail/index";
export { default as TourCountry } from "./TourCountry/index";
export { default as TourForeign } from "./TourForeign/index";
export { default as Payment } from "./Payment/Payment";
export { default as Introduce } from "./Introduce/Introduce";
